import { StyleSheet } from "react-native";

export const AppStyle = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: "#0F0F23",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#1E1E3F",
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: 0.5,
  },
  subtitle: {
    fontSize: 15,
    color: "#8B9DC3",
    marginBottom: 12,
    fontWeight: "500",
  },
  chatContainer: {
    flex: 1,
    paddingHorizontal: 4,
  },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  message: {
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
    maxWidth: "80%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  userMessage: {
    backgroundColor: "#3B82F6",
    alignSelf: "flex-end",
  },
  assistantMessage: {
    backgroundColor: "#1E293B",
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#334155",
  },
  systemMessage: {
    backgroundColor: "#1E40AF",
    alignSelf: "center",
  },
  messageText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "400",
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingTop: 16,
    paddingHorizontal: 4,
    backgroundColor: "#0F0F23",
    borderTopWidth: 1,
    borderTopColor: "#1E1E3F",
  },
  input: {
    flex: 1,
    borderWidth: 2,
    borderColor: "#374151",
    backgroundColor: "#1F2937",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: "#FFFFFF",
    fontSize: 16,
    minHeight: 48,
  },
  inputFocused: {
    borderColor: "#60A5FA",
    shadowColor: "#60A5FA",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  sendButton: {
    backgroundColor: "#3B82F6",
    borderRadius: 12,
    padding: 12,
    minWidth: 48,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  sendButtonDisabled: {
    backgroundColor: "#374151",
    opacity: 0.6,
  },
});
